name: flutter_razorpay_web
description: Package for razorpay web is designed to facilitate smooth integration of Razorpay's payment gateway services specifically for web-based Flutter applications.
version: 0.0.2
repository: https://github.com/priyaranjan12345/flutter_razorpay_web
homepage: https://github.com/priyaranjan12345

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  test: ^1.24.3

flutter:
  plugin:
    platforms:
      web:
        default_package: flutter_razorpay_web